### PR TITLE
Added Shadcn, TailwindCSS, ReactRouter, and Express server

### PR DESCRIPTION
**Pull request by WebDevMcFarland**
Added Shadcn, TailwindCSS, ReactRouter, and Express server : Connected component Tree.

### CODE REVIEW

**Review by DanielGaran02 — APPROVED** [review]
Great skeleton, really well done. Great Job!!

**Review by anthonyHerr — APPROVED** [review]
Awesome job! Really nice work Jacob. You got a ton done!

**Review by stan-louie — APPROVED** [review]
Great start, approved!

**Review by julesdmai — APPROVED** [review]
That's a fine looking skeleton. Great job McFarland!

**Pull request merged**
